### ISSUE TITLE
how to insert dynamic values into data

### ISSUE THREAD

**Issue by sovathchhinh** [bsadnu/yii2-googlecharts#1]
I got an issue of how to insert dynamic value to data.
Please check at this  ?????"$piechartprovince"???????

$piechartprovince ='';
                $rows = PiechartByProvinces::find()->all();
                if(!empty($rows))
                {
                  foreach($rows as $row)
                  {
                    $piechartprovince .= '['.$row->pro_name.",".round($row->SubTotal,0).'],';
                  }
                }
                echo $piechartprovince;
                ?>
                <?= PieChart::widget([
                    'id' => 'my-pie-chart-id',
                    'data' => [
                                  ?????"$piechartprovince"???????
                                  // ['Major', 'Degrees'],
                                  // ['Business', 256070],
                                  // ['Education', 108034],
                                  // ['Social Sciences & History', 127101],
                                  // ['Health', 81863],
                                  // ['Psychology', 74194],
                    ],
                    'options' => [
                        'fontName' => 'Verdana',
                        'height' => 300,
                        'width' => 500,
                        'chartArea' => [
                            'left' => 50,
                            'width' => '100%',
                            'height' => '100%',
                            ],
                        'is3D'=>true,
                        'colors'=>['#4799B5', '#94A545','#D37D28', '#403B33','#E6E7E8',"#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850","#FF0000","#FFA500","#FFFF00","#808000","#008000","#FF00FF"],
                        'responsive'=>true,
                        'maintainAspectRatio'=>false,
                        'legend' => [
                            'position' => 'left',
                            'alignment' => 'top',
                        ]
                    ]
                ]) ?>

**Comment by bsadnu** [comment]
Hey @sovathchhinh !
It is not connected with extension itself. Try to make data exactly like in example:
    'data' => [
        ['Major', 'Degrees'],
        ['Business', 256070],
        ['Education', 108034],
        ['Social Sciences & History', 127101],
        ['Health', 81863],
        ['Psychology', 74194]
    ],`
`
Take a look onto PHP explode(), implode()
