### ISSUE TITLE
I cannot see the geochart map

### ISSUE THREAD

**Issue by murat0404** [bsadnu/yii2-googlecharts#8]
I have a geochart problem please help I cannot see the maps

**Comment by bsadnu** [comment]
@murat0404 add some details, please. Logs, screenshots etc.

**Comment by murat0404** [comment]
![Screenshot_20200810_101325.jpg](https://user-images.githubusercontent.com/69384021/89759155-31c29d00-daf2-11ea-92e7-b370c8309e57.jpg).  It doesn't look like this![IMG_20200803_234228.jpg](https://user-images.githubusercontent.com/69384021/89759827-b661eb00-daf3-11ea-90a6-bac3cb4448bf.jpg)

**Comment by bsadnu** [comment]
@murat0404 but where is your PHP code?

**Comment by murat0404** [comment]
Script do I need to send all

**Comment by bsadnu** [comment]
@murat0404 yep. Can not say anything without seeing a code.

**Comment by murat0404** [comment]
The size of the muscles is big, if I give you a link

**Comment by bsadnu** [comment]
@murat0404 just send a code where you exactly use the widget

**Comment by murat0404** [comment]
here

**Comment by murat0404** [comment]
[geochart.zip](https://github.com/bsadnu/yii2-googlecharts/files/5053227/geochart.zip)
